# Generated by Django 6.0.3 on 2026-04-24 02:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0002_initial'),
        ('invoicing', '0003_change_clave_unidad_fk_to_claveunidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rfc', models.CharField(db_index=True, help_text='RFC del emisor (CFDI 4.0)', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^([A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3})$', message='RFC inválido')])),
                ('legal_name', models.CharField(help_text='Nombre/Razón social EXACTO como en la CSF (CFDI 4.0)', max_length=255)),
                ('person_type', models.CharField(choices=[('FISICA', 'Persona física'), ('MORAL', 'Persona moral')], max_length=6)),
                ('tax_zip', models.CharField(help_text='Código postal del domicilio fiscal (CFDI 4.0)', max_length=10)),
                ('commercial_name', models.CharField(blank=True, max_length=255)),
                ('email_billing', models.EmailField(blank=True, max_length=254)),
                ('email_contact', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logos/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Variante para fondos oscuros', null=True, upload_to='company/logos/')),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('primary_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Color HEX inválido (#RRGGBB)')])),
                ('secondary_color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}){1,2}$', 'Color HEX inválido (#RRGGBB)')])),
                ('legal_representative', models.CharField(blank=True, max_length=255)),
                ('company_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='entities.companysector')),
                ('country', models.ForeignKey(default='MEX', on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='entities.country')),
                ('tax_regime', models.ForeignKey(help_text='Régimen fiscal del emisor (CFDI 4.0)', limit_choices_to={'catalog': 'c_RegimenFiscal'}, on_delete=django.db.models.deletion.PROTECT, related_name='companies_regimen', to='invoicing.satcatalog')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('FISCAL', 'Fiscal'), ('BRANCH', 'Sucursal'), ('SHIPPING', 'Envío'), ('OTHER', 'Otra')], default='FISCAL', max_length=10)),
                ('name', models.CharField(blank=True, help_text='Etiqueta de la dirección (ej. "Oficina CDMX")', max_length=120)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('ext_no', models.CharField(blank=True, max_length=50)),
                ('int_no', models.CharField(blank=True, max_length=50)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='administration.company')),
                ('country', models.ForeignKey(default='MEX', on_delete=django.db.models.deletion.PROTECT, related_name='company_addresses', to='entities.country')),
            ],
            options={
                'verbose_name': 'Dirección de Empresa',
                'verbose_name_plural': 'Direcciones de Empresa',
            },
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('clabe', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('^\\d{18}$', 'CLABE debe tener 18 dígitos')])),
                ('account_holder', models.CharField(blank=True, help_text='Titular de la cuenta (si difiere de la razón social)', max_length=255)),
                ('swift_code', models.CharField(blank=True, max_length=11)),
                ('is_primary', models.BooleanField(default=False)),
                ('bank', models.ForeignKey(limit_choices_to={'catalog': 'c_Banco'}, on_delete=django.db.models.deletion.PROTECT, to='invoicing.satcatalog')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='administration.company')),
                ('currency', models.ForeignKey(blank=True, limit_choices_to={'catalog': 'c_Moneda'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_bank_accounts', to='invoicing.satcatalog')),
            ],
            options={
                'verbose_name': 'Cuenta bancaria de Empresa',
                'verbose_name_plural': 'Cuentas bancarias de Empresa',
            },
        ),
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('serial_number', models.CharField(db_index=True, help_text='Número de serie del certificado (NoCertificado en CFDI)', max_length=40)),
                ('cer_file', models.FileField(help_text='Archivo .cer del SAT', upload_to='company/csd/cer/')),
                ('key_file', models.FileField(help_text='Archivo .key del SAT', upload_to='company/csd/key/')),
                ('password', models.CharField(help_text='Contraseña del CSD (debe almacenarse cifrada)', max_length=255)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='administration.company')),
            ],
            options={
                'verbose_name': 'Certificado CSD',
                'verbose_name_plural': 'Certificados CSD',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('phone_landline', models.CharField(blank=True, max_length=30)),
                ('phone_landline_ext', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'No especificado')], default='N', max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='company/contacts/')),
                ('is_primary', models.BooleanField(default=False, help_text='Contacto principal de la empresa')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='administration.company')),
                ('job_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_contacts', to='entities.jobposition')),
                ('person_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_contacts', to='entities.persontitle')),
            ],
            options={
                'verbose_name': 'Contacto de Empresa',
                'verbose_name_plural': 'Contactos de Empresa',
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('rfc',), name='uniq_company_rfc'),
        ),
        migrations.AddIndex(
            model_name='companyaddress',
            index=models.Index(fields=['company', 'kind'], name='administrat_company_753770_idx'),
        ),
        migrations.AddIndex(
            model_name='companybankaccount',
            index=models.Index(fields=['company', 'bank'], name='administrat_company_6e1209_idx'),
        ),
        migrations.AddConstraint(
            model_name='companybankaccount',
            constraint=models.UniqueConstraint(fields=('company', 'clabe'), name='uniq_company_clabe'),
        ),
        migrations.AddConstraint(
            model_name='companycertificate',
            constraint=models.UniqueConstraint(fields=('company', 'serial_number'), name='uniq_company_csd_serial'),
        ),
        migrations.AddIndex(
            model_name='companycontact',
            index=models.Index(fields=['company', 'email'], name='administrat_company_f25cd1_idx'),
        ),
    ]
