# Generated by Django 6.0.3 on 2026-04-24 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('entities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entities.bank'),
        ),
    ]
