services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
    env_file:
      - .env
    networks:
      - core_gateway_network
      - default
    expose:
      - "8000"

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_files:/app/staticfiles:ro
      - media_files:/app/media:ro
    depends_on:
      - web

volumes:
  static_files:
  media_files:

networks:
  core_gateway_network:
    external: true
