# Generated by Django 6.0.3 on 2026-05-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identificador estable (ej: 'partner', 'department').", max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('plural_name', models.CharField(max_length=120)),
                ('model', models.CharField(blank=True, default='', help_text="Alias del modelo backend (ej: 'partner').", max_length=120)),
                ('module', models.CharField(blank=True, default='', help_text="Id del módulo al que pertenece (ej: 'entities', 'core').", max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.JSONField(blank=True, default=list)),
                ('search_attributes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entity Model',
                'verbose_name_plural': 'Entity Models',
                'db_table': 'core_entity_model',
                'ordering': ['module', 'code'],
            },
        ),
    ]
