# Generated by Django 6.0.3 on 2026-05-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entitymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitymodel',
            options={'ordering': ['code'], 'verbose_name': 'Entity Model', 'verbose_name_plural': 'Entity Models'},
        ),
        migrations.RemoveField(
            model_name='entitymodel',
            name='module',
        ),
    ]
