# Generated by Django 6.0.3 on 2026-05-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_entitymodel_options_remove_entitymodel_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=40)),
                ('font_family', models.CharField(default='system', max_length=80)),
                ('currency_code', models.CharField(default='MXN', max_length=10)),
                ('locale', models.CharField(default='es-MX', max_length=20)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_settings', to='core.account')),
            ],
            options={
                'verbose_name': 'Account Platform Settings',
                'verbose_name_plural': 'Account Platform Settings',
                'db_table': 'core_account_platform_settings',
            },
        ),
    ]
