# Generated by Django 6.0.2 on 2026-03-18 18:13

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SatCatalog',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('catalog', models.CharField(db_index=True, max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo SAT',
                'verbose_name_plural': 'Catálogos SAT',
            },
        ),
        migrations.CreateModel(
            name='ClaveProdServ',
            fields=[
                ('clave', models.CharField(help_text='Clave de 8 dígitos proporcionada por el SAT', max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Descripción oficial del producto o servicio')),
                ('incluir_iva_trasladado', models.CharField(blank=True, help_text="Indicador de IVA trasladado (Ej. 'Sí', 'No', 'Opcional')", max_length=10, null=True)),
                ('incluir_ieps_trasladado', models.CharField(blank=True, help_text='Indicador de IEPS trasladado', max_length=10, null=True)),
                ('palabras_similares', models.TextField(blank=True, help_text='Palabras clave para facilitar la búsqueda en el ERP', null=True)),
            ],
            options={
                'verbose_name': 'Clave Producto/Servicio SAT',
                'verbose_name_plural': 'Claves Productos/Servicios SAT',
                'db_table': 'sat_claveprodserv',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['descripcion'], name='clave_desc_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='ClaveUnidad',
            fields=[
                ('clave', models.CharField(help_text='Clave de unidad proporcionada por el SAT', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la unidad de medida', max_length=255)),
            ],
            options={
                'verbose_name': 'Clave Unidad SAT',
                'verbose_name_plural': 'Claves Unidades SAT',
                'db_table': 'sat_claveunidad',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='claveunidad_name_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.pricelist')),
            ],
            options={
                'verbose_name': 'Price List Item',
                'verbose_name_plural': 'Price List Items',
                'ordering': ['price_list', 'product_variation'],
            },
        ),
    ]
