# Generated by Django 6.0.3 on 2026-04-15 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='resources.prodservvariation'),
        ),
        migrations.AddField(
            model_name='prodservvariationsat',
            name='clave_prod_serv',
            field=models.ForeignKey(blank=True, help_text='Clave de Producto/Servicio SAT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variation_sat', to='invoicing.claveprodserv'),
        ),
        migrations.AlterUniqueTogether(
            name='satcatalog',
            unique_together={('catalog', 'code')},
        ),
        migrations.AddField(
            model_name='prodservvariationsat',
            name='clave_unidad',
            field=models.ForeignKey(blank=True, help_text='Clave de Unidad SAT', limit_choices_to={'catalog': 'c_ClaveUnidad'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variation_sat_unidad', to='invoicing.satcatalog'),
        ),
        migrations.AddField(
            model_name='prodservvariationsat',
            name='objeto_imp',
            field=models.ForeignKey(blank=True, help_text='Objeto de impuesto (01, 02, etc.)', limit_choices_to={'catalog': 'c_ObjetoImp'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variation_sat_objeto_imp', to='invoicing.satcatalog'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('price_list', 'product_variation')},
        ),
    ]
