# Generated by Django 6.0.2 on 2026-03-12 05:03

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='ClaveProdServ',
            fields=[
                ('clave', models.CharField(help_text='Clave de 8 dígitos proporcionada por el SAT', max_length=8, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text='Descripción oficial del producto o servicio')),
                ('incluir_iva_trasladado', models.CharField(blank=True, help_text="Indicador de IVA trasladado (Ej. 'Sí', 'No', 'Opcional')", max_length=10, null=True)),
                ('incluir_ieps_trasladado', models.CharField(blank=True, help_text='Indicador de IEPS trasladado', max_length=10, null=True)),
                ('palabras_similares', models.TextField(blank=True, help_text='Palabras clave para facilitar la búsqueda en el ERP', null=True)),
            ],
            options={
                'verbose_name': 'Clave Producto/Servicio SAT',
                'verbose_name_plural': 'Claves Productos/Servicios SAT',
                'db_table': 'sat_claveprodserv',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['descripcion'], name='clave_desc_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
