# Generated by Django 6.0.2 on 2026-03-18 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='product_variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='resources.productvariation'),
        ),
        migrations.AddIndex(
            model_name='satcatalog',
            index=models.Index(fields=['catalog', 'code'], name='invoicing_s_catalog_9132df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistitem',
            unique_together={('price_list', 'product_variation')},
        ),
    ]
