# Generated by Django 6.0.2 on 2026-03-12 21:54

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_claveprodserv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveUnidad',
            fields=[
                ('clave', models.CharField(help_text='Clave de unidad proporcionada por el SAT', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre de la unidad de medida', max_length=255)),
            ],
            options={
                'verbose_name': 'Clave Unidad SAT',
                'verbose_name_plural': 'Claves Unidades SAT',
                'db_table': 'sat_claveunidad',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['name'], name='claveunidad_name_gin_idx', opclasses=['gin_trgm_ops'])],
            },
        ),
    ]
