# Generated by Django 6.0.3 on 2026-04-16 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodservvariationsat',
            name='clave_unidad',
            field=models.ForeignKey(blank=True, help_text='Clave de Unidad SAT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variation_sat_unidad', to='invoicing.claveunidad'),
        ),
    ]
