# Generated by Django 6.0.2 on 2026-03-04 07:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Sector',
                'verbose_name_plural': 'Company Sectors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Position',
                'verbose_name_plural': 'Job Positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('FISCAL', 'Fiscal'), ('SHIPPING', 'Envío'), ('OTHER', 'Otra')], default='FISCAL', max_length=10)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('ext_no', models.CharField(blank=True, max_length=50)),
                ('int_no', models.CharField(blank=True, max_length=50)),
                ('neighborhood', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Dirección de Partner',
                'verbose_name_plural': 'Direcciones de Partner',
            },
        ),
        migrations.CreateModel(
            name='PartnerBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clabe', models.CharField(max_length=18)),
                ('account_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Cuenta bancaria de Partner',
                'verbose_name_plural': 'Cuentas bancarias de Partner',
            },
        ),
        migrations.CreateModel(
            name='PartnerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Contacto de Partner',
                'verbose_name_plural': 'Contactos de Partner',
            },
        ),
        migrations.CreateModel(
            name='PartnerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CUSTOMER', 'Cliente'), ('SUPPLIER', 'Proveedor'), ('CARRIER', 'Transportista'), ('OTHER', 'Otro')], max_length=20)),
                ('payment_terms_days', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rol de Partner',
                'verbose_name_plural': 'Roles de Partner',
            },
        ),
        migrations.CreateModel(
            name='PersonTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Person Title',
                'verbose_name_plural': 'Person Titles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^([A-ZÑ&]{3,4}\\d{6}[A-Z0-9]{3})$', message='RFC inválido')])),
                ('legal_name', models.CharField(help_text='Nombre/Razón social EXACTO como en la CSF (CFDI 4.0)', max_length=255)),
                ('person_type', models.CharField(choices=[('FISICA', 'Persona física'), ('MORAL', 'Persona moral')], max_length=6)),
                ('tax_zip', models.CharField(help_text='Código postal del domicilio fiscal (CFDI 4.0)', max_length=10)),
                ('commercial_name', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/logos/')),
                ('email_billing', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(default='MEX', on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='entities.country')),
            ],
            options={
                'verbose_name': 'Partner (Entidad)',
                'verbose_name_plural': 'Partners (Entidades)',
            },
        ),
    ]
