# Generated by Django 6.0.2 on 2026-03-12 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tax_regime',
            field=models.ForeignKey(help_text='Régimen fiscal del contribuyente (CFDI 4.0)', limit_choices_to={'catalog': 'c_RegimenFiscal'}, on_delete=django.db.models.deletion.PROTECT, related_name='partners_regimen', to='invoicing.satcatalog'),
        ),
        migrations.AddField(
            model_name='partneraddress',
            name='country',
            field=models.ForeignKey(default='MEX', on_delete=django.db.models.deletion.PROTECT, related_name='partner_addresses', to='entities.country'),
        ),
        migrations.AddField(
            model_name='partneraddress',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='entities.partner'),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='bank',
            field=models.ForeignKey(limit_choices_to={'catalog': 'c_Banco'}, on_delete=django.db.models.deletion.PROTECT, to='invoicing.satcatalog'),
        ),
        migrations.AddField(
            model_name='partnerbankaccount',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='entities.partner'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_contacts', to='entities.jobposition'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='entities.partner'),
        ),
        migrations.AddField(
            model_name='partnerrole',
            name='default_currency',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog': 'c_Moneda'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerrole_currency', to='invoicing.satcatalog'),
        ),
        migrations.AddField(
            model_name='partnerrole',
            name='diot_operation_type',
            field=models.ForeignKey(blank=True, help_text='DIOT: tipo de operación (02, 03, 06, 85, 87…). Solo proveedores.', limit_choices_to={'catalog': 'DIOT_TipoOperacion'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerrole_diot_operacion', to='invoicing.satcatalog'),
        ),
        migrations.AddField(
            model_name='partnerrole',
            name='diot_third_type',
            field=models.ForeignKey(blank=True, help_text='DIOT: tipo de tercero (04 Nacional, 05 Extranjero, 15 Global). Solo proveedores.', limit_choices_to={'catalog': 'DIOT_TipoTercero'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partnerrole_diot_tercero', to='invoicing.satcatalog'),
        ),
        migrations.AddField(
            model_name='partnerrole',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='entities.partner'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='person_title',
            field=models.ForeignKey(blank=True, help_text='Título personal (Ing., Lic., Dr., etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='entities.persontitle'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['rfc'], name='entities_pa_rfc_0916e9_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['active'], name='entities_pa_active_fb20b5_idx'),
        ),
        migrations.AddIndex(
            model_name='partneraddress',
            index=models.Index(fields=['partner', 'kind'], name='entities_pa_partner_293acc_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerbankaccount',
            index=models.Index(fields=['partner', 'bank'], name='entities_pa_partner_807a1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerrole',
            unique_together={('partner', 'role')},
        ),
        migrations.AddIndex(
            model_name='partnercontact',
            index=models.Index(fields=['partner', 'email'], name='entities_pa_partner_cebb75_idx'),
        ),
    ]
