# Generated by Django 6.0.2 on 2026-03-19 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company_sector',
            field=models.ForeignKey(blank=True, help_text='Sector/giro de la empresa (Tecnología, Educación, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='entities.companysector'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sector',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Privado'), ('PUBLIC', 'Público')], default='', help_text='Sector del partner: Privado o Público', max_length=10),
        ),
    ]
