# Generated by Django 6.0.2 on 2026-03-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_partner_company_sector_partner_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercontact',
            name='phone_landline',
            field=models.CharField(blank=True, default='', help_text='Teléfono fijo', max_length=30),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='phone_landline_ext',
            field=models.CharField(blank=True, default='', help_text='Extensión del teléfono fijo', max_length=10),
        ),
    ]
