# Generated by Django 6.0.2 on 2026-03-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercontact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/contacts/'),
        ),
    ]
