# Generated by Django 6.0.2 on 2026-03-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_partnercontact_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercontact',
            name='role',
        ),
        migrations.AddField(
            model_name='partner',
            name='person_title',
            field=models.ForeignKey(blank=True, help_text='Título personal (Ing., Lic., Dr., etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='entities.persontitle'),
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_contacts', to='entities.jobposition'),
        ),
    ]
