# Generated by Django 6.0.2 on 2026-03-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_remove_partnercontact_role_partner_person_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='person_title',
        ),
        migrations.AddField(
            model_name='partnercontact',
            name='person_title',
            field=models.ForeignKey(blank=True, help_text='Título personal (Ing., Lic., Dr., etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partners', to='entities.persontitle'),
        ),
    ]
