# Generated by Django 6.0.2 on 2026-03-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_remove_partner_person_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercontact',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'No especificado')], default='N', max_length=1),
        ),
    ]
