# Generated by Django 6.0.2 on 2026-03-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference'),
        ),
    ]
