# Generated by Django 6.0.3 on 2026-04-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodserv',
            name='partners',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='entities.partner'),
        ),
    ]
