# Generated by Django 6.0.3 on 2026-04-16 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_prodserv_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodserv',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='resources.brand'),
        ),
    ]
