# Generated by Django 6.0.3 on 2026-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_prodserv_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prodservvariation',
            options={'ordering': ['product'], 'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
        migrations.AlterField(
            model_name='prodservvariation',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
