# Generated by Django 6.0.3 on 2026-04-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_initial'),
        ('resources', '0004_alter_prodservvariation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodserv',
            name='partners',
            field=models.ManyToManyField(related_name='products', to='entities.partner'),
        ),
    ]
