# Generated by Django 6.0.3 on 2026-04-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_initial'),
        ('resources', '0005_alter_prodserv_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodserv',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='products', to='entities.partner'),
        ),
    ]
