# Generated by Django 6.0.3 on 2026-04-15 17:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FastQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, default='', help_text='Nombre auxiliar del cliente (sin necesidad de tener un Partner registrado)', max_length=200)),
                ('description', models.CharField(blank=True, default='', help_text='Asunto o título de la cotización', max_length=300)),
                ('date', models.DateField(help_text='Fecha de emisión de la cotización')),
                ('validity_date', models.DateField(blank=True, help_text='Fecha de vencimiento / vigencia', null=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=20)),
                ('amount_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal antes de impuestos', max_digits=14)),
                ('amount_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de descuento', max_digits=14)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de impuestos', max_digits=14)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de la cotización', max_digits=14)),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Notas internas (solo visibles para el equipo)')),
                ('external_notes', models.TextField(blank=True, default='', help_text='Notas externas (visibles para el cliente)')),
                ('currency', models.ForeignKey(help_text='Moneda (catálogo SAT c_Moneda)', limit_choices_to={'catalog': 'c_Moneda'}, on_delete=django.db.models.deletion.PROTECT, related_name='fast_quotations_currency', to='invoicing.satcatalog')),
                ('salesperson', models.ForeignKey(blank=True, help_text='Vendedor responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fast Quotation',
                'verbose_name_plural': 'Fast Quotations',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FastQuotationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=10, help_text='Orden de la línea en la cotización')),
                ('description', models.CharField(blank=True, default='', help_text='Descripción personalizada (override del producto)', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Porcentaje de impuesto (ej. 16 para IVA 16%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fast_quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.fastquotation')),
                ('product_variation', models.ForeignKey(help_text='Variación de producto cotizada', on_delete=django.db.models.deletion.PROTECT, related_name='fast_quotation_lines', to='resources.prodservvariation')),
                ('unit_of_measure', models.ForeignKey(help_text='Unidad de medida SAT', on_delete=django.db.models.deletion.PROTECT, related_name='fast_quotation_lines', to='invoicing.claveunidad')),
            ],
            options={
                'verbose_name': 'Fast Quotation Line',
                'verbose_name_plural': 'Fast Quotation Lines',
                'ordering': ['fast_quotation', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='FastSalesProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Nombre de la propuesta de venta', max_length=200)),
                ('objective', models.TextField(blank=True, default='', help_text='Objetivo de la propuesta de venta')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción general de la propuesta')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_progress', 'En progreso'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=20)),
                ('partner', models.ForeignKey(blank=True, help_text='Cliente asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_sales_proposals', to='entities.partner')),
                ('partner_contact', models.ForeignKey(blank=True, help_text='Contacto del cliente (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_sales_proposals', to='entities.partnercontact')),
                ('salesperson', models.ForeignKey(blank=True, help_text='Vendedor responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fast_sales_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fast Sales Proposal',
                'verbose_name_plural': 'Fast Sales Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fastquotation',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Propuesta de venta a la que pertenece esta cotización (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.fastsalesproposal'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number', models.CharField(db_index=True, help_text='Número de cotización (ej. QTN-0001)', max_length=30, unique=True)),
                ('reference', models.CharField(blank=True, default='', help_text='Referencia del cliente o número de solicitud', max_length=100)),
                ('date', models.DateField(help_text='Fecha de emisión de la cotización')),
                ('validity_date', models.DateField(blank=True, help_text='Fecha de vencimiento / vigencia', null=True)),
                ('expected_closing_date', models.DateField(blank=True, help_text='Fecha esperada de cierre', null=True)),
                ('payment_terms_days', models.PositiveIntegerField(default=0, help_text='Días de crédito')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=20)),
                ('amount_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal antes de impuestos', max_digits=14)),
                ('amount_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto total de descuento', max_digits=14)),
                ('amount_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de impuestos', max_digits=14)),
                ('amount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total de la cotización', max_digits=14)),
                ('notes', models.TextField(blank=True, default='', help_text='Notas internas')),
                ('terms_and_conditions', models.TextField(blank=True, default='', help_text='Términos y condiciones visibles al cliente')),
                ('currency', models.ForeignKey(help_text='Moneda (catálogo SAT c_Moneda)', limit_choices_to={'catalog': 'c_Moneda'}, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_currency', to='invoicing.satcatalog')),
                ('partner', models.ForeignKey(help_text='Cliente al que se emite la cotización', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='entities.partner')),
                ('partner_contact', models.ForeignKey(blank=True, help_text='Contacto del cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='entities.partnercontact')),
                ('payment_form', models.ForeignKey(blank=True, help_text='Forma de pago SAT (01, 02, etc.)', limit_choices_to={'catalog': 'c_FormaPago'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_payment_form', to='invoicing.satcatalog')),
                ('payment_method', models.ForeignKey(blank=True, help_text='Método de pago SAT (PUE, PPD)', limit_choices_to={'catalog': 'c_MetodoPago'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations_payment_method', to='invoicing.satcatalog')),
                ('price_list', models.ForeignKey(blank=True, help_text='Lista de precios aplicada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='invoicing.pricelist')),
                ('salesperson', models.ForeignKey(blank=True, help_text='Vendedor responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, help_text='Dirección de envío', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='entities.partneraddress')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'ordering': ['-date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveIntegerField(default=10, help_text='Orden de la línea en la cotización')),
                ('description', models.CharField(blank=True, default='', help_text='Descripción personalizada (override del producto)', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de descuento (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_percent', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Porcentaje de impuesto (ej. 16 para IVA 16%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('product_variation', models.ForeignKey(help_text='Variación de producto cotizada', on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='resources.prodservvariation')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.quotation')),
                ('unit_of_measure', models.ForeignKey(help_text='Unidad de medida SAT', on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='invoicing.claveunidad')),
            ],
            options={
                'verbose_name': 'Quotation Line',
                'verbose_name_plural': 'Quotation Lines',
                'ordering': ['quotation', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='fastsalesproposal',
            index=models.Index(fields=['status'], name='sales_fasts_status_bacebd_idx'),
        ),
        migrations.AddIndex(
            model_name='fastquotation',
            index=models.Index(fields=['status'], name='sales_fastq_status_5ae6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='fastquotation',
            index=models.Index(fields=['date'], name='sales_fastq_date_5d05d1_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['partner', 'status'], name='sales_quota_partner_e34ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['date'], name='sales_quota_date_842d7e_idx'),
        ),
    ]
