# Generated by Django 6.0.3 on 2026-04-21 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_prodserv_partners'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fastquotationline',
            old_name='unit_of_measure',
            new_name='clave_unidad',
        ),
        migrations.RemoveField(
            model_name='fastquotationline',
            name='product_variation',
        ),
        migrations.AddField(
            model_name='fastquotationline',
            name='product_service_variation',
            field=models.ForeignKey(default=1, help_text='Variación de producto o servicio cotizada', on_delete=django.db.models.deletion.PROTECT, related_name='fast_quotation_lines', to='resources.prodservvariation'),
            preserve_default=False,
        ),
    ]
