# Generated by Django 6.0.3 on 2026-04-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_unit_of_measure_fastquotationline_clave_unidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='terms_and_conditions',
            new_name='external_notes',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='notes',
            new_name='internal_notes',
        ),
        migrations.RenameField(
            model_name='quotationline',
            old_name='unit_of_measure',
            new_name='clave_unidad',
        ),
        migrations.RenameField(
            model_name='quotationline',
            old_name='product_variation',
            new_name='product_service_variation',
        ),
    ]
