# Generated by Django 6.0.2 on 2026-03-31 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_fastquotation_fastquotationline_fastsalesproposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastquotation',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Propuesta de venta a la que pertenece esta cotización (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.fastsalesproposal'),
        ),
    ]
