# Generated by Django 6.0.3 on 2026-05-04 19:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_terms_and_conditions_quotation_external_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalNoteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(db_index=True, help_text='Código único de la plantilla (ej. NOTE-001)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo de la plantilla', max_length=150)),
                ('template', models.TextField(help_text='Contenido HTML de la nota externa (texto enriquecido)')),
            ],
            options={
                'verbose_name': 'Plantilla de nota externa',
                'verbose_name_plural': 'Plantillas de notas externas',
                'ordering': ['code'],
            },
        ),
    ]
