# Generated by Django 6.0.3 on 2026-05-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_externalnotetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationDailySequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_date', models.DateField(db_index=True, unique=True)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Quotation Daily Sequence',
                'verbose_name_plural': 'Quotation Daily Sequences',
            },
        ),
    ]
