# Generated by Django 6.0.3 on 2026-05-06 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_initial'),
        ('sales', '0005_quotationdailysequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Nombre de la propuesta de venta', max_length=200)),
                ('objective', models.TextField(blank=True, default='', help_text='Objetivo de la propuesta de venta')),
                ('description', models.TextField(blank=True, default='', help_text='Descripción general de la propuesta')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_progress', 'En progreso'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], db_index=True, default='draft', max_length=20)),
                ('partner', models.ForeignKey(blank=True, help_text='Cliente asociado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_proposals', to='entities.partner')),
                ('partner_contact', models.ForeignKey(blank=True, help_text='Contacto del cliente (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_proposals', to='entities.partnercontact')),
                ('salesperson', models.ForeignKey(blank=True, help_text='Vendedor responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Proposal',
                'verbose_name_plural': 'Sales Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='proposal',
            field=models.ForeignKey(blank=True, help_text='Propuesta de venta a la que pertenece esta cotización (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.salesproposal'),
        ),
        migrations.AddIndex(
            model_name='salesproposal',
            index=models.Index(fields=['status'], name='sales_sales_status_2432b8_idx'),
        ),
    ]
